### ISSUE TITLE
Allow donors to choose a range

### ISSUE THREAD

**Issue by thenickcox** [humanutility/detroit-water-project#5]
I just signed up to be a donor, but until I get the email, it's not clear to me how much I'll be asked to give. It'd be great to select an amount when I put in my email. 

I could help implement this if needed.

**Comment by tiffani** [comment]
Good idea, Nick! Pushing this out shortly. Will close and let you know when it's up!

**Comment by tiffani** [comment]
Got it in! Closed by: 2e5738e645815af7f543d06b4887ec3b1d729e19

**Comment by thenickcox** [comment]
:thumbsup:  Thanks, @tiffani! Great project.
